[project]
name = "api-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xuhao", email = "690278565@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
api-server = "api_server:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
